// Mocks generated by Mockito 5.4.4 from annotations
// in currency_converter_task/test/home/data/repositories/home_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:currency_converter_task/features/Home/data/local/data_sources/home_local_data_source.dart'
    as _i5;
import 'package:currency_converter_task/features/Home/data/remote/data_sources/home_remote_data_source.dart'
    as _i2;
import 'package:currency_converter_task/features/Home/data/remote/models/currencies_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HomeRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRemoteDataSource extends _i1.Mock
    implements _i2.HomeRemoteDataSource {
  @override
  _i3.Future<List<_i4.CurrencyModel>> getCurrencies() => (super.noSuchMethod(
        Invocation.method(
          #getCurrencies,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.CurrencyModel>>.value(<_i4.CurrencyModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.CurrencyModel>>.value(<_i4.CurrencyModel>[]),
      ) as _i3.Future<List<_i4.CurrencyModel>>);

  @override
  _i3.Future<num> getConversionRate(
    String? from,
    String? to,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConversionRate,
          [
            from,
            to,
          ],
        ),
        returnValue: _i3.Future<num>.value(0),
        returnValueForMissingStub: _i3.Future<num>.value(0),
      ) as _i3.Future<num>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getHistoricalRates(
    String? from,
    String? to,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHistoricalRates,
          [
            from,
            to,
          ],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [HomeLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeLocalDataSource extends _i1.Mock
    implements _i5.HomeLocalDataSource {
  @override
  _i3.Future<List<_i4.CurrencyModel>> getCurrencies() => (super.noSuchMethod(
        Invocation.method(
          #getCurrencies,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.CurrencyModel>>.value(<_i4.CurrencyModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.CurrencyModel>>.value(<_i4.CurrencyModel>[]),
      ) as _i3.Future<List<_i4.CurrencyModel>>);

  @override
  _i3.Future<List<_i4.CurrencyModel>> saveCurrencies(
          List<_i4.CurrencyModel>? currencies) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCurrencies,
          [currencies],
        ),
        returnValue:
            _i3.Future<List<_i4.CurrencyModel>>.value(<_i4.CurrencyModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.CurrencyModel>>.value(<_i4.CurrencyModel>[]),
      ) as _i3.Future<List<_i4.CurrencyModel>>);
}
