name: currency_converter_task
description: "A Currency Converter App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  envied: ^0.5.3
  bloc: ^8.1.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  darty_commons: ^1.0.2
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  injectable: ^2.3.2
  chopper: ^7.1.1
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.1
  chopper_generator: ^7.1.1
  envied_generator: ^0.5.3
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
