// Mocks generated by Mockito 5.4.4 from annotations
// in currency_converter_task/test/home/data/data_sources/remote_data_source/home_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:chopper/chopper.dart' as _i3;
import 'package:currency_converter_task/core/network/service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeType_0 extends _i1.SmartFake implements Type {
  _FakeType_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NetworkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkService extends _i1.Mock implements _i2.NetworkService {
  @override
  _i3.ChopperClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _i4.dummyValue<_i3.ChopperClient>(
          this,
          Invocation.getter(#client),
        ),
        returnValueForMissingStub: _i4.dummyValue<_i3.ChopperClient>(
          this,
          Invocation.getter(#client),
        ),
      ) as _i3.ChopperClient);

  @override
  set client(_i3.ChopperClient? _client) => super.noSuchMethod(
        Invocation.setter(
          #client,
          _client,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Type get definitionType => (super.noSuchMethod(
        Invocation.getter(#definitionType),
        returnValue: _FakeType_0(
          this,
          Invocation.getter(#definitionType),
        ),
        returnValueForMissingStub: _FakeType_0(
          this,
          Invocation.getter(#definitionType),
        ),
      ) as Type);

  @override
  _i5.Future<_i3.Response<dynamic>> getSupportedCurrencies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSupportedCurrencies,
          [],
        ),
        returnValue: _i5.Future<_i3.Response<dynamic>>.value(
            _i4.dummyValue<_i3.Response<dynamic>>(
          this,
          Invocation.method(
            #getSupportedCurrencies,
            [],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.Response<dynamic>>.value(
            _i4.dummyValue<_i3.Response<dynamic>>(
          this,
          Invocation.method(
            #getSupportedCurrencies,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Response<dynamic>>);

  @override
  _i5.Future<_i3.Response<dynamic>> getLatestRates(
    String? from,
    List<String>? to,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLatestRates,
          [
            from,
            to,
          ],
        ),
        returnValue: _i5.Future<_i3.Response<dynamic>>.value(
            _i4.dummyValue<_i3.Response<dynamic>>(
          this,
          Invocation.method(
            #getLatestRates,
            [
              from,
              to,
            ],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.Response<dynamic>>.value(
            _i4.dummyValue<_i3.Response<dynamic>>(
          this,
          Invocation.method(
            #getLatestRates,
            [
              from,
              to,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Response<dynamic>>);

  @override
  _i5.Future<_i3.Response<dynamic>> getHistoricalRates(
    String? from,
    List<String>? to,
    String? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHistoricalRates,
          [
            from,
            to,
            date,
          ],
        ),
        returnValue: _i5.Future<_i3.Response<dynamic>>.value(
            _i4.dummyValue<_i3.Response<dynamic>>(
          this,
          Invocation.method(
            #getHistoricalRates,
            [
              from,
              to,
              date,
            ],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.Response<dynamic>>.value(
            _i4.dummyValue<_i3.Response<dynamic>>(
          this,
          Invocation.method(
            #getHistoricalRates,
            [
              from,
              to,
              date,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Response<dynamic>>);
}
